### ISSUE TITLE
Prepare for 0.32 release

### ISSUE THREAD

**Issue by bdraco** [jstasiak/python-zeroconf#643]
- [x] Async feature complete https://github.com/jstasiak/python-zeroconf/issues/642

- [x] Unicast cover https://github.com/jstasiak/python-zeroconf/issues/572

- [x] Change log update https://github.com/jstasiak/python-zeroconf/pull/684

- [x] Example update to show async usage

- [x] Fix fate sharing for additionals. If we send an answer QU, the additional should always go with it not be multicast.  _handlers will need to track which additionals belong with which answers and then de-dupe at the end.  https://github.com/jstasiak/python-zeroconf/issues/689

- [x] Add QU example https://github.com/jstasiak/python-zeroconf/issues/702 (https://github.com/postlund/pyatv/issues/951#issuecomment-863124213) https://github.com/jstasiak/python-zeroconf/pull/719

- [x] HAP-python https://github.com/ikalchev/HAP-python/pull/349

- [x] Home Assistant https://github.com/home-assistant/core/pull/51173

- [x] aiohomekit https://github.com/Jc2k/aiohomekit/pull/39

- [x] Additional production testing

- [x] document threadsafety and fix source of truth issues https://github.com/jstasiak/python-zeroconf/issues/720

- [x] Changelog updates after example added

- [x] run everything through objgraph to detect any memory leaks 

- [x] 0.32.0b1 tag for testers

- [x] 0.32.0b1 beta testing

- [x] 0.32.0b2 beta testing

- [x] 0.32.0b3 beta testing
 
- [x] 0.32.0b4 beta testing

- [x] 0.32.0b5 beta testing

- [x] Mitigate denial of service https://github.com/jstasiak/python-zeroconf/issues/823 https://github.com/jstasiak/python-zeroconf/issues/825

- [x] 0.32.0b6 beta testing

- [x] 0.32.0rc1 production testing

- [x] 0.32.0rc2 production testing

- [x] 0.32.0rc3 production testing

- [x] 0.32.0rc4 production testing

- [x] 0.32.0rc5 production testing

- [x] Write multi thread torture test

- [x] 0.32.0rc6 production testing

- [x] 100% line and branch coverage

- [x] 0.32.0rc7 production testing

- [x] Reformat changelog https://github.com/jstasiak/python-zeroconf/issues/880

- [x] Remove internal refactoring from changelog https://github.com/jstasiak/python-zeroconf/issues/881

- [x] Collapse 0.32.0 changelog https://github.com/jstasiak/python-zeroconf/issues/882

- [x] Disable pylint in CI https://github.com/jstasiak/python-zeroconf/issues/884

- [x] Try to rename zeorconf.aio back to zeroconf.asyncio https://github.com/jstasiak/python-zeroconf/issues/883

**Comment by bdraco** [comment]
Netdisco will need to be update as well as it reads the cache directly.

**Comment by bdraco** [comment]
Memory looks good

```
2021-06-21 03:39:40 CRITICAL (SyncWorker_8) [homeassistant.components.profiler] Memory Growth: [('weakref', 16321, 110), ('TimerHandle', 176, 51), ('Context', 1010, 29), ('SplitResult', 42, 12), ('HassJob', 1029, 2), ('LogEntry', 5, 1)]
2021-06-21 03:40:10 CRITICAL (SyncWorker_2) [homeassistant.components.profiler] Memory Growth: [('weakref', 16368, 47), ('SplitResult', 44, 2), ('builtin_function_or_method', 6436, 1), ('frozenset', 1008, 1), ('WSMessage', 10, 1), ('KeyedRef', 185, 1), ('Quoter', 1, 1)]
2021-06-21 03:40:40 CRITICAL (SyncWorker_10) [homeassistant.components.profiler] Memory Growth: [('WSMessage', 22, 12)]
2021-06-21 03:41:10 CRITICAL (SyncWorker_0) [homeassistant.components.profiler] Memory Growth: []

```

**Comment by bdraco** [comment]
Memory retest looks good

```
021-06-24 13:28:27 CRITICAL (SyncWorker_13) [homeassistant.components.profiler] Memory Growth: [('HomekitControllerFlowHandler', 4, 1)]
2021-06-24 13:28:57 CRITICAL (SyncWorker_11) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:29:27 CRITICAL (SyncWorker_14) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:29:57 CRITICAL (SyncWorker_13) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:30:27 CRITICAL (SyncWorker_14) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:30:57 CRITICAL (SyncWorker_13) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:31:27 CRITICAL (SyncWorker_3) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:31:57 CRITICAL (SyncWorker_14) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:32:27 CRITICAL (SyncWorker_10) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:32:57 CRITICAL (SyncWorker_15) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:33:27 CRITICAL (SyncWorker_11) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:33:57 CRITICAL (SyncWorker_10) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:34:27 CRITICAL (SyncWorker_13) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:34:57 CRITICAL (SyncWorker_2) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:35:27 CRITICAL (SyncWorker_14) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:35:57 CRITICAL (SyncWorker_17) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:36:27 CRITICAL (SyncWorker_15) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:36:57 CRITICAL (SyncWorker_14) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:37:27 CRITICAL (SyncWorker_3) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:37:57 CRITICAL (SyncWorker_6) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:38:27 CRITICAL (SyncWorker_10) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:38:57 CRITICAL (SyncWorker_3) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:39:27 CRITICAL (SyncWorker_12) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:39:57 CRITICAL (SyncWorker_9) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:40:27 CRITICAL (SyncWorker_2) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:40:57 CRITICAL (SyncWorker_12) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:41:27 CRITICAL (SyncWorker_13) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:41:57 CRITICAL (SyncWorker_2) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:42:27 CRITICAL (SyncWorker_14) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:42:57 CRITICAL (SyncWorker_4) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:43:27 CRITICAL (SyncWorker_8) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:43:57 CRITICAL (SyncWorker_14) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:44:27 CRITICAL (SyncWorker_15) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:44:57 CRITICAL (SyncWorker_3) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:45:27 CRITICAL (SyncWorker_0) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:45:57 CRITICAL (SyncWorker_8) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:46:27 CRITICAL (SyncWorker_9) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:46:57 CRITICAL (SyncWorker_0) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:47:27 CRITICAL (SyncWorker_9) [homeassistant.components.profiler] Memory Growth: [('SpotifyFlowHandler', 1, 1)]
2021-06-24 13:47:57 CRITICAL (SyncWorker_0) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:48:27 CRITICAL (SyncWorker_10) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:48:57 CRITICAL (SyncWorker_6) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:49:27 CRITICAL (SyncWorker_16) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:49:57 CRITICAL (SyncWorker_2) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:50:27 CRITICAL (SyncWorker_15) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:50:57 CRITICAL (SyncWorker_16) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:51:27 CRITICAL (SyncWorker_12) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:51:57 CRITICAL (SyncWorker_15) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:52:27 CRITICAL (SyncWorker_4) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:52:57 CRITICAL (SyncWorker_0) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:53:27 CRITICAL (SyncWorker_14) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:53:57 CRITICAL (SyncWorker_12) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:54:27 CRITICAL (SyncWorker_9) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:54:57 CRITICAL (SyncWorker_14) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:55:27 CRITICAL (SyncWorker_6) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:55:57 CRITICAL (SyncWorker_9) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:56:27 CRITICAL (SyncWorker_8) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:56:57 CRITICAL (SyncWorker_6) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:57:27 CRITICAL (SyncWorker_13) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:57:57 CRITICAL (SyncWorker_5) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:58:27 CRITICAL (SyncWorker_0) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:58:57 CRITICAL (SyncWorker_8) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:59:27 CRITICAL (SyncWorker_14) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 13:59:57 CRITICAL (SyncWorker_0) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 14:00:27 CRITICAL (SyncWorker_13) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 14:00:57 CRITICAL (SyncWorker_5) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 14:01:27 CRITICAL (SyncWorker_4) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 14:01:57 CRITICAL (SyncWorker_13) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 14:02:27 CRITICAL (SyncWorker_14) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 14:02:57 CRITICAL (SyncWorker_13) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 14:03:27 CRITICAL (SyncWorker_12) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 14:03:57 CRITICAL (SyncWorker_4) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 14:04:27 CRITICAL (SyncWorker_10) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 14:04:57 CRITICAL (SyncWorker_12) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 14:05:27 CRITICAL (SyncWorker_17) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 14:05:57 CRITICAL (SyncWorker_10) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 14:06:27 CRITICAL (SyncWorker_0) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 14:06:57 CRITICAL (SyncWorker_17) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 14:07:27 CRITICAL (SyncWorker_0) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 14:07:57 CRITICAL (SyncWorker_17) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 14:08:27 CRITICAL (SyncWorker_9) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 14:08:57 CRITICAL (SyncWorker_0) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 14:09:27 CRITICAL (SyncWorker_13) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 14:09:57 CRITICAL (SyncWorker_9) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 14:10:27 CRITICAL (SyncWorker_15) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 14:10:57 CRITICAL (SyncWorker_13) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 14:11:27 CRITICAL (SyncWorker_10) [homeassistant.components.profiler] Memory Growth: []
2021-06-24 14:11:57 CRITICAL (SyncWorker_15) [homeassistant.components.profiler] Memory Growth: []
```
